// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.33.4
// source: proto/face_recognition.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	FaceRecognitionService_RegisterEmployee_FullMethodName = "/face_recognition.FaceRecognitionService/RegisterEmployee"
	FaceRecognitionService_RecognizeFace_FullMethodName    = "/face_recognition.FaceRecognitionService/RecognizeFace"
	FaceRecognitionService_LogAttendance_FullMethodName    = "/face_recognition.FaceRecognitionService/LogAttendance"
	FaceRecognitionService_ListEmployees_FullMethodName    = "/face_recognition.FaceRecognitionService/ListEmployees"
)

// FaceRecognitionServiceClient is the client API for FaceRecognitionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FaceRecognitionServiceClient interface {
	// Registrar nuevo empleado con foto
	RegisterEmployee(ctx context.Context, in *RegisterEmployeeRequest, opts ...grpc.CallOption) (*RegisterEmployeeResponse, error)
	// Reconocer persona en foto/video
	RecognizeFace(ctx context.Context, in *RecognizeFaceRequest, opts ...grpc.CallOption) (*RecognizeFaceResponse, error)
	// Registrar asistencia
	LogAttendance(ctx context.Context, in *AttendanceRequest, opts ...grpc.CallOption) (*AttendanceResponse, error)
	// Obtener empleados registrados
	ListEmployees(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*EmployeeList, error)
}

type faceRecognitionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFaceRecognitionServiceClient(cc grpc.ClientConnInterface) FaceRecognitionServiceClient {
	return &faceRecognitionServiceClient{cc}
}

func (c *faceRecognitionServiceClient) RegisterEmployee(ctx context.Context, in *RegisterEmployeeRequest, opts ...grpc.CallOption) (*RegisterEmployeeResponse, error) {
	out := new(RegisterEmployeeResponse)
	err := c.cc.Invoke(ctx, FaceRecognitionService_RegisterEmployee_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *faceRecognitionServiceClient) RecognizeFace(ctx context.Context, in *RecognizeFaceRequest, opts ...grpc.CallOption) (*RecognizeFaceResponse, error) {
	out := new(RecognizeFaceResponse)
	err := c.cc.Invoke(ctx, FaceRecognitionService_RecognizeFace_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *faceRecognitionServiceClient) LogAttendance(ctx context.Context, in *AttendanceRequest, opts ...grpc.CallOption) (*AttendanceResponse, error) {
	out := new(AttendanceResponse)
	err := c.cc.Invoke(ctx, FaceRecognitionService_LogAttendance_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *faceRecognitionServiceClient) ListEmployees(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*EmployeeList, error) {
	out := new(EmployeeList)
	err := c.cc.Invoke(ctx, FaceRecognitionService_ListEmployees_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FaceRecognitionServiceServer is the server API for FaceRecognitionService service.
// All implementations must embed UnimplementedFaceRecognitionServiceServer
// for forward compatibility
type FaceRecognitionServiceServer interface {
	// Registrar nuevo empleado con foto
	RegisterEmployee(context.Context, *RegisterEmployeeRequest) (*RegisterEmployeeResponse, error)
	// Reconocer persona en foto/video
	RecognizeFace(context.Context, *RecognizeFaceRequest) (*RecognizeFaceResponse, error)
	// Registrar asistencia
	LogAttendance(context.Context, *AttendanceRequest) (*AttendanceResponse, error)
	// Obtener empleados registrados
	ListEmployees(context.Context, *Empty) (*EmployeeList, error)
	mustEmbedUnimplementedFaceRecognitionServiceServer()
}

// UnimplementedFaceRecognitionServiceServer must be embedded to have forward compatible implementations.
type UnimplementedFaceRecognitionServiceServer struct {
}

func (UnimplementedFaceRecognitionServiceServer) RegisterEmployee(context.Context, *RegisterEmployeeRequest) (*RegisterEmployeeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterEmployee not implemented")
}
func (UnimplementedFaceRecognitionServiceServer) RecognizeFace(context.Context, *RecognizeFaceRequest) (*RecognizeFaceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecognizeFace not implemented")
}
func (UnimplementedFaceRecognitionServiceServer) LogAttendance(context.Context, *AttendanceRequest) (*AttendanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LogAttendance not implemented")
}
func (UnimplementedFaceRecognitionServiceServer) ListEmployees(context.Context, *Empty) (*EmployeeList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListEmployees not implemented")
}
func (UnimplementedFaceRecognitionServiceServer) mustEmbedUnimplementedFaceRecognitionServiceServer() {
}

// UnsafeFaceRecognitionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FaceRecognitionServiceServer will
// result in compilation errors.
type UnsafeFaceRecognitionServiceServer interface {
	mustEmbedUnimplementedFaceRecognitionServiceServer()
}

func RegisterFaceRecognitionServiceServer(s grpc.ServiceRegistrar, srv FaceRecognitionServiceServer) {
	s.RegisterService(&FaceRecognitionService_ServiceDesc, srv)
}

func _FaceRecognitionService_RegisterEmployee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterEmployeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FaceRecognitionServiceServer).RegisterEmployee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FaceRecognitionService_RegisterEmployee_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FaceRecognitionServiceServer).RegisterEmployee(ctx, req.(*RegisterEmployeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FaceRecognitionService_RecognizeFace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecognizeFaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FaceRecognitionServiceServer).RecognizeFace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FaceRecognitionService_RecognizeFace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FaceRecognitionServiceServer).RecognizeFace(ctx, req.(*RecognizeFaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FaceRecognitionService_LogAttendance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttendanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FaceRecognitionServiceServer).LogAttendance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FaceRecognitionService_LogAttendance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FaceRecognitionServiceServer).LogAttendance(ctx, req.(*AttendanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FaceRecognitionService_ListEmployees_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FaceRecognitionServiceServer).ListEmployees(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FaceRecognitionService_ListEmployees_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FaceRecognitionServiceServer).ListEmployees(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// FaceRecognitionService_ServiceDesc is the grpc.ServiceDesc for FaceRecognitionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FaceRecognitionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "face_recognition.FaceRecognitionService",
	HandlerType: (*FaceRecognitionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterEmployee",
			Handler:    _FaceRecognitionService_RegisterEmployee_Handler,
		},
		{
			MethodName: "RecognizeFace",
			Handler:    _FaceRecognitionService_RecognizeFace_Handler,
		},
		{
			MethodName: "LogAttendance",
			Handler:    _FaceRecognitionService_LogAttendance_Handler,
		},
		{
			MethodName: "ListEmployees",
			Handler:    _FaceRecognitionService_ListEmployees_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/face_recognition.proto",
}
