# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: face_recognition.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'face_recognition.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x66\x61\x63\x65_recognition.proto\x12\x10\x66\x61\x63\x65_recognition\"K\n\x17RegisterEmployeeRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x65mployee_id\x18\x02 \x01(\t\x12\r\n\x05image\x18\x03 \x01(\x0c\"<\n\x18RegisterEmployeeResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"%\n\x14RecognizeFaceRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\"T\n\x15RecognizeFaceResponse\x12\x12\n\nrecognized\x18\x01 \x01(\x08\x12\x13\n\x0b\x65mployee_id\x18\x02 \x01(\t\x12\x12\n\nconfidence\x18\x03 \x01(\x02\"(\n\x11\x41ttendanceRequest\x12\x13\n\x0b\x65mployee_id\x18\x01 \x01(\t\"6\n\x12\x41ttendanceResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x07\n\x05\x45mpty\"-\n\x08\x45mployee\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x65mployee_id\x18\x02 \x01(\t\"=\n\x0c\x45mployeeList\x12-\n\temployees\x18\x01 \x03(\x0b\x32\x1a.face_recognition.Employee2\x8b\x03\n\x16\x46\x61\x63\x65RecognitionService\x12i\n\x10RegisterEmployee\x12).face_recognition.RegisterEmployeeRequest\x1a*.face_recognition.RegisterEmployeeResponse\x12`\n\rRecognizeFace\x12&.face_recognition.RecognizeFaceRequest\x1a\'.face_recognition.RecognizeFaceResponse\x12Z\n\rLogAttendance\x12#.face_recognition.AttendanceRequest\x1a$.face_recognition.AttendanceResponse\x12H\n\rListEmployees\x12\x17.face_recognition.Empty\x1a\x1e.face_recognition.EmployeeListB2Z0github.com/example/face-attendance/backend/pb;pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'face_recognition_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z0github.com/example/face-attendance/backend/pb;pb'
  _globals['_REGISTEREMPLOYEEREQUEST']._serialized_start=44
  _globals['_REGISTEREMPLOYEEREQUEST']._serialized_end=119
  _globals['_REGISTEREMPLOYEERESPONSE']._serialized_start=121
  _globals['_REGISTEREMPLOYEERESPONSE']._serialized_end=181
  _globals['_RECOGNIZEFACEREQUEST']._serialized_start=183
  _globals['_RECOGNIZEFACEREQUEST']._serialized_end=220
  _globals['_RECOGNIZEFACERESPONSE']._serialized_start=222
  _globals['_RECOGNIZEFACERESPONSE']._serialized_end=306
  _globals['_ATTENDANCEREQUEST']._serialized_start=308
  _globals['_ATTENDANCEREQUEST']._serialized_end=348
  _globals['_ATTENDANCERESPONSE']._serialized_start=350
  _globals['_ATTENDANCERESPONSE']._serialized_end=404
  _globals['_EMPTY']._serialized_start=406
  _globals['_EMPTY']._serialized_end=413
  _globals['_EMPLOYEE']._serialized_start=415
  _globals['_EMPLOYEE']._serialized_end=460
  _globals['_EMPLOYEELIST']._serialized_start=462
  _globals['_EMPLOYEELIST']._serialized_end=523
  _globals['_FACERECOGNITIONSERVICE']._serialized_start=526
  _globals['_FACERECOGNITIONSERVICE']._serialized_end=921
# @@protoc_insertion_point(module_scope)
