# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import face_recognition_pb2 as face__recognition__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in face_recognition_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FaceRecognitionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterEmployee = channel.unary_unary(
                '/face_recognition.FaceRecognitionService/RegisterEmployee',
                request_serializer=face__recognition__pb2.RegisterEmployeeRequest.SerializeToString,
                response_deserializer=face__recognition__pb2.RegisterEmployeeResponse.FromString,
                _registered_method=True)
        self.RecognizeFace = channel.unary_unary(
                '/face_recognition.FaceRecognitionService/RecognizeFace',
                request_serializer=face__recognition__pb2.RecognizeFaceRequest.SerializeToString,
                response_deserializer=face__recognition__pb2.RecognizeFaceResponse.FromString,
                _registered_method=True)
        self.LogAttendance = channel.unary_unary(
                '/face_recognition.FaceRecognitionService/LogAttendance',
                request_serializer=face__recognition__pb2.AttendanceRequest.SerializeToString,
                response_deserializer=face__recognition__pb2.AttendanceResponse.FromString,
                _registered_method=True)
        self.ListEmployees = channel.unary_unary(
                '/face_recognition.FaceRecognitionService/ListEmployees',
                request_serializer=face__recognition__pb2.Empty.SerializeToString,
                response_deserializer=face__recognition__pb2.EmployeeList.FromString,
                _registered_method=True)


class FaceRecognitionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterEmployee(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecognizeFace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LogAttendance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListEmployees(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FaceRecognitionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterEmployee': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterEmployee,
                    request_deserializer=face__recognition__pb2.RegisterEmployeeRequest.FromString,
                    response_serializer=face__recognition__pb2.RegisterEmployeeResponse.SerializeToString,
            ),
            'RecognizeFace': grpc.unary_unary_rpc_method_handler(
                    servicer.RecognizeFace,
                    request_deserializer=face__recognition__pb2.RecognizeFaceRequest.FromString,
                    response_serializer=face__recognition__pb2.RecognizeFaceResponse.SerializeToString,
            ),
            'LogAttendance': grpc.unary_unary_rpc_method_handler(
                    servicer.LogAttendance,
                    request_deserializer=face__recognition__pb2.AttendanceRequest.FromString,
                    response_serializer=face__recognition__pb2.AttendanceResponse.SerializeToString,
            ),
            'ListEmployees': grpc.unary_unary_rpc_method_handler(
                    servicer.ListEmployees,
                    request_deserializer=face__recognition__pb2.Empty.FromString,
                    response_serializer=face__recognition__pb2.EmployeeList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'face_recognition.FaceRecognitionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('face_recognition.FaceRecognitionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FaceRecognitionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterEmployee(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/face_recognition.FaceRecognitionService/RegisterEmployee',
            face__recognition__pb2.RegisterEmployeeRequest.SerializeToString,
            face__recognition__pb2.RegisterEmployeeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecognizeFace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/face_recognition.FaceRecognitionService/RecognizeFace',
            face__recognition__pb2.RecognizeFaceRequest.SerializeToString,
            face__recognition__pb2.RecognizeFaceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LogAttendance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/face_recognition.FaceRecognitionService/LogAttendance',
            face__recognition__pb2.AttendanceRequest.SerializeToString,
            face__recognition__pb2.AttendanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListEmployees(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/face_recognition.FaceRecognitionService/ListEmployees',
            face__recognition__pb2.Empty.SerializeToString,
            face__recognition__pb2.EmployeeList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
